"""add icon to goal

Revision ID: 0ff13790c18c
Revises: 73875a8e320a
Create Date: 2024-04-08 08:41:42.428941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  


# revision identifiers, used by Alembic.
revision: str = '0ff13790c18c'
down_revision: Union[str, None] = '73875a8e320a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('icon', sa.String(), nullable=True))
    op.create_index(op.f('ix_goals_icon'), 'goals', ['icon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goals_icon'), table_name='goals')
    op.drop_column('goals', 'icon')
    # ### end Alembic commands ###
