"""categories

Revision ID: ed0e10868a8b
Revises: 0f9215d4d15d
Create Date: 2023-12-15 21:45:02.075142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed0e10868a8b'
down_revision: Union[str, None] = '0f9215d4d15d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_categories_id'), 'task_categories', ['id'], unique=False)
    op.create_index(op.f('ix_task_categories_name'), 'task_categories', ['name'], unique=True)
    op.drop_index('ix_completed_tasks_id', table_name='completed_tasks')
    op.drop_index('ix_completed_tasks_title', table_name='completed_tasks')
    op.drop_table('completed_tasks')
    op.drop_index('ix_failed_tasks_id', table_name='failed_tasks')
    op.drop_index('ix_failed_tasks_title', table_name='failed_tasks')
    op.drop_table('failed_tasks')
    op.add_column('tasks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'task_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'category_id')
    op.create_table('failed_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('failed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='failed_tasks_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='failed_tasks_pkey')
    )
    op.create_index('ix_failed_tasks_title', 'failed_tasks', ['title'], unique=False)
    op.create_index('ix_failed_tasks_id', 'failed_tasks', ['id'], unique=False)
    op.create_table('completed_tasks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='completed_tasks_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='completed_tasks_pkey')
    )
    op.create_index('ix_completed_tasks_title', 'completed_tasks', ['title'], unique=False)
    op.create_index('ix_completed_tasks_id', 'completed_tasks', ['id'], unique=False)
    op.drop_index(op.f('ix_task_categories_name'), table_name='task_categories')
    op.drop_index(op.f('ix_task_categories_id'), table_name='task_categories')
    op.drop_table('task_categories')
    # ### end Alembic commands ###
