"""completed tasks

Revision ID: f2404e03d16a
Revises: c5f0374bb857
Create Date: 2023-12-12 18:31:26.505349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  


# revision identifiers, used by Alembic.
revision: str = 'f2404e03d16a'
down_revision: Union[str, None] = 'c5f0374bb857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_tasks_id'), 'completed_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_completed_tasks_title'), 'completed_tasks', ['title'], unique=False)
    op.create_table('failed_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_tasks_id'), 'failed_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_failed_tasks_title'), 'failed_tasks', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_tasks_title'), table_name='failed_tasks')
    op.drop_index(op.f('ix_failed_tasks_id'), table_name='failed_tasks')
    op.drop_table('failed_tasks')
    op.drop_index(op.f('ix_completed_tasks_title'), table_name='completed_tasks')
    op.drop_index(op.f('ix_completed_tasks_id'), table_name='completed_tasks')
    op.drop_table('completed_tasks')
    # ### end Alembic commands ###
